// 按需导入vant组件
import Vue from 'vue'
import { Tab, Tabs, Checkbox, Dialog, ActionSheet, Icon, Search, Swipe, SwipeItem, Grid, GridItem, Toast, Button, Switch, Rate, Tabbar, TabbarItem, NavBar, Skeleton, Divider, GoodsAction, GoodsActionIcon, GoodsActionButton, SubmitBar, CountDown, Cell, CellGroup, Popup, AddressList, Collapse, CollapseItem, Field, Loading, Tag, Uploader } from 'vant'

Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Icon)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Rate)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Skeleton)
Vue.use(Divider)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(GoodsActionButton)
Vue.use(SubmitBar)
Vue.use(CountDown)
Vue.use(Cell)
Vue.use(Popup)
Vue.use(AddressList)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Field)
Vue.use(CellGroup)
Vue.use(Loading)
Vue.use(Tag)
Vue.use(Uploader)
