/**
 * Vant UI - 移动端组件库按需导入模块
 * 核心功能：
 * 1. 统一管理项目中使用的 Vant 组件
 * 2. 减少打包体积，提升加载速度
 */
import Vue from 'vue'
import { Lazyload, Tab, Tabs, Checkbox, Dialog, ActionSheet, Icon, Search, Swipe, SwipeItem, Grid, GridItem, Toast, Button, Switch, Rate, Tabbar, TabbarItem, NavBar, Skeleton, Divider, GoodsAction, GoodsActionIcon, GoodsActionButton, SubmitBar, CountDown, Cell, CellGroup, Popup, AddressList, Collapse, CollapseItem, Field, Loading, Tag, Uploader, Empty, Radio, RadioGroup, DropdownMenu, DropdownItem, AddressEdit, PullRefresh, List } from 'vant'

Vue.use(Lazyload)
Vue.use(PullRefresh)
Vue.use(List)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Icon)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Rate)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Skeleton)
Vue.use(Divider)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(GoodsActionButton)
Vue.use(SubmitBar)
Vue.use(CountDown)
Vue.use(Cell)
Vue.use(Popup)
Vue.use(AddressList)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Field)
Vue.use(CellGroup)
Vue.use(Loading)
Vue.use(Tag)
Vue.use(Uploader)
Vue.use(Empty)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(AddressEdit)
